
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const Chat = lazy(() => import("./pages/Chat.tsx"));
const ForgotPassword = lazy(() => import("./pages/ForgotPassword.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Profile = lazy(() => import("./pages/Profile.tsx"));
const Register = lazy(() => import("./pages/Register.tsx"));
const ResetPassword = lazy(() => import("./pages/ResetPassword.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/chat", element: <Chat />},
	{ path: "/forgot-password", element: <ForgotPassword />},
	{ path: "/forgotpassword", element: <ForgotPassword />},
	{ path: "/login", element: <Login />},
	{ path: "/profile", element: <Profile />},
	{ path: "/register", element: <Register />},
	{ path: "/reset-password", element: <ResetPassword />},
	{ path: "/resetpassword", element: <ResetPassword />},

];
